# Generated by Django 5.2.9 on 2026-01-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrolerule',
            options={'verbose_name': 'Правило-доступа', 'verbose_name_plural': 'Правила-доступа'},
        ),
        migrations.AlterModelOptions(
            name='businesselement',
            options={'verbose_name': 'Бизнес-объект', 'verbose_name_plural': 'Бизнес-объекты'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сессия', 'verbose_name_plural': 'Сессии'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
